Add removal of unmapped groups
IMQS/authaus pull request #48
Opened 2020-12-08 16:36 UTC by bosvos

2020-12-09 08:56 UTC, jasonkofo requested changes

2020-12-09 08:56 UTC, jasonkofo commented on msaad.go
> +	m.parent.Log.Debugf("MSAAD empty role arrays constructed")
```suggestion
	if m.parent.MSAAD.Config.Verbose {
    	    m.parent.Log.Debugf("MSAAD empty role arrays constructed")
    	}
```

2020-12-09 08:56 UTC, jasonkofo commented on msaad.go
> +		m.parent.Log.Debugf("MSAAD checking all roles: %v", internalGroupName)
I think this class of logs should not be allowed to bloat the configs, unless we explicitly want them. So I will just let you know all of the logs that I am sure should be masked behind verbose config.
```suggestion
		if m.parent.MSAAD.Config.Verbose {
		    m.parent.Log.Debugf("MSAAD checking all roles: %v", internalGroupName)
		}
```

2020-12-09 08:56 UTC, jasonkofo commented on msaad.go
> +		m.parent.Log.Debugf("MSAAD checking default roles: %v", groupName)
Mask behind verbose config

2020-12-09 08:56 UTC, jasonkofo commented on msaad.go
> +		m.parent.Log.Debugf("MSAAD add allowed default ID for %v", groupName)
Mask behind verbose config

2020-12-09 08:56 UTC, jasonkofo commented on msaad.go
> +			m.parent.Log.Debugf("MSAAD unmapped ID %v, add to remove list", groupID)
Mask behind verbose config

2020-12-09 08:56 UTC, jasonkofo commented on msaad.go
> +			groupName := group.Name
Superfluous creation of the variable here. Rather just pass the ltype in the next line.

2020-12-09 10:10 UTC, bosvos commented
Changes made - please review.

2021-01-20 12:01 UTC, bosvos commented
@jasonkofo I suppose we need to get this into master.

2021-01-20 12:10 UTC, jasonkofo requested changes
Seriously minor issues that I have

2021-01-20 12:10 UTC, jasonkofo commented on msaad.go
> +		allowedIDs = append(allowedIDs, internalGroup.ID)
Please excuse my being pedantic about issues of style
```suggestion
		if internalGroup, ok := roleGroups.nameToGroup[internalGroupName]; ok {
		    m.parent.Log.Debugf("MSAAD add allowed ID for %v", internalGroupName)
		    allowedIDs = append(allowedIDs, internalGroup.ID)
		}
```

2021-01-20 12:10 UTC, jasonkofo commented on msaad.go
> +	m.parent.Log.Debugf("MSAAD syncRoles started for %s", nameInLogs)
A part of me thinks that including this at a debug level will introduce LOADS of noise into the logs, especially if one is expecting 120something of these records every 3 minutes

I wanna recommend that we drop the log level of this one. 
```suggestion
	m.parent.Log.Tracef("MSAAD syncRoles started for %s", nameInLogs)
```

2021-01-20 12:10 UTC, jasonkofo commented on msaad.go
> +		m.parent.Log.Debugf("MSAAD add allowed ID for %v", internalGroupName)
```suggestion
		m.parent.Log.Tracef("MSAAD add allowed ID for %v", internalGroupName)
```

2021-02-17 09:30 UTC, jasonkofo approved these changes

2021-02-17 15:11 UTC, merged