INF-1305 export user groups json
IMQS/authaus pull request #49
Opened 2021-04-20 09:04 UTC by nkosimarz

Get raw groups from db for export groups (and users in groups) to json

2021-04-20 15:06 UTC, FritzOnFire requested changes
Some minor changes, but LGTM

2021-04-20 15:06 UTC, FritzOnFire commented on roledb.go
> +		groups = append(groups, RawAuthGroup{ID: id, Name: name, PermList: permList})
So for this you can just create the `RawAuthGroup` and then use it for the scan. Like
```go
r = RawAuthGroup{}
Scan(&r.id, &r.name, r.permList)
```
Makes things a bit simpler.

2021-04-20 15:06 UTC, FritzOnFire commented on roledb.go
> +	return groups, nil
As discussed, this should just be the one liner returning the result of the function.

2021-04-23 11:50 UTC, FritzOnFire approved these changes
LGTM

2021-04-28 13:56 UTC, jasonkofo approved these changes

2021-04-29 13:24 UTC, jasonkofo approved these changes

2021-04-29 13:24 UTC, merged